### ISSUE TITLE
Change Project Name?

### ISSUE THREAD

**Issue by johnkferguson** [johnkferguson/octomaps#1]
GithubMaps is just an initial name for the project. I imagine we can come up with a better project name. Suggest any ideas here.

@meowist @mrikhter

**Comment by johnkferguson** [comment]
Octomaps?

**Comment by meowist** [comment]
I like octomaps. I've named our heroku Sinatra app octomaps but can change it if Masha doesn't like it.

**Comment by aviflombaum** [comment]
octomaps is pretty awesome. +1

Avi Flombaum
http://twitter.com/aviflombaum
