### ISSUE TITLE
Can't Push to Update Heroku

### ISSUE THREAD

**Issue by johnkferguson** [johnkferguson/octomaps#16]
Justin set up a heroku app for octomaps. Masha and I have all been added as collaborators. We have made changes to our local branch and pushed them to master. Now we want to take those changes and push them to heroku.

We have typed in `git push heroku master` and gotten the following error:

```
 [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@heroku.com:octomaps.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

So we need to figure out how to be able to push to heroku.

@aviflombaum @meowist @mrikhter

**Comment by meowist** [comment]
Some more context for @aviflombaum

John and Masha are both getting this error. I am not.

Heroku is also saying it's synced up with GitHub master, but when we deploy
Heroku (which so far only I am able to do), the version we get is outdated.
So Herouk master is not tracking GHub master.

**Comment by johnkferguson** [comment]
It seems to be all working now, going to close this issue.
