### ISSUE TITLE
Dev / Stage / Prod server config

### ISSUE THREAD

**Issue by meowist** [johnkferguson/octomaps#18]
Our current config--deploying straight to prod!--is not a best practice. If we continue to work on this app, we should set up subdomains like

dev.octomaps.com: for all development in progress
stage.octomaps.com: for use in reviewing deployed changes pre-prod release
prod (www): for releasing final changes to the public

Def not necessary for Thursday, but wanted to log this issue.

**Comment by meowist** [comment]
Looping in @aviflombaum in case he has advice on best way to approach this. Gets very complicated with multiple Git repos etc. so we should all discuss. 

@mrikhter @JohnKellyFerguson

**Comment by aviflombaum** [comment]
Ya staging and Dev in production require more effort, Not worth it right now
