### ISSUE TITLE
Build randomly fails because of location-based lookups

### ISSUE THREAD

**Issue by dblock** [johnkferguson/octomaps#31]
[This build](https://travis-ci.org/JohnKellyFerguson/octomaps) failed because of location lookups against a real service. I think sometimes they return results and sometimes they run into some kind of error (like quota or whatever).

Should be recorded via VCR for tests.

**Comment by johnkferguson** [comment]
[This commit](https://github.com/JohnKellyFerguson/octomaps/commit/8dc5296b0133928288d26a5489c81812c1b82b40) and [this commit](https://github.com/JohnKellyFerguson/octomaps/commit/fc3cacab9c28bead7cd4ce974f67de2405d9a8b4) fix the issue.

I wrote all of the original tests a while back when I didn't really understand mocking or stubbing. As a consequence, any time I saved a `Location` object, it triggered a geocode callback to Google. 

So I went ahead and stubbed out the `geocode_location` method in the tests to prevent this. I also refactored a bunch of specs to remove a lot of unnecessary database reads and writes. This reduced the total test time from 9 to 1.5 seconds. 

Currently, all of the interactions with external services (Github & Google) are not being tested, so this is something I'll have to address later.
