### ISSUE TITLE
Location Lookup Still Queries Github even if we have a user in the database

### ISSUE THREAD

**Issue by johnkferguson** [johnkferguson/octomaps#8]
Even if we have a user in our database, the location lookup method still queries github.

The code we wrote to try and prevent this doesn't work, so I have commented out but left it in, so we can refer to it.

I've pushed these changes to master. So master still works as it did previously, however, we haven't been able how to figure out how to stop the unnecessary github api requests.

@aviflombaum @mrikhter @meowist

**Comment by meowist** [comment]
I think the prob here is that our db_check method doesn't actually check the database. I ran it with pry and found that it always returns false. I added a puts statement to have it 'talk to us' and on every repo I tried it returned "user found in database." So I think we need to refactor this method. Working on that now. Here's a screenshot of the version I used to debug:

http://gyazo.com/e11a375d81f0b365060e353c95740c63

**Comment by johnkferguson** [comment]
We got it all fixed. Awesome!
